services:
  app:
    build:
      dockerfile: ./docker/app/Dockerfile
      target: app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      HOST_UID: '${HOST_UID}'
      HOST_GID: '${HOST_GID}'

  server:
    build:
      dockerfile: ./docker/server/Dockerfile
      target: server
    extra_hosts:
      - 'host.docker.interal:host-gateway'
    environment:
      SERVER_NAME: '${SERVER_NAME:-localhost}'
      SERVER_PORT: '${SERVER_PORT:-80}'
      APP_NAME: app
      APP_PORT: 9000
      WEB_ROOT: /var/www/html/public

  cache:
    build:
      dockerfile: ./docker/cache/Dockerfile
      target: cache
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s
      start_period: 5s
      interval: 5s

  browser:
    build:
      dockerfile: ./docker/browser/Dockerfile
      target: browser
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '/dev/shm:/dev/shm'
